#!/bin/bash

R=$(tput setaf 1)
G=$(tput setaf 2)
Y=$(tput setaf 3)
N=$(tput sgr0)
BOLD=$(tput bold)

WRONG="${R}✗ Wrong$N"
CORRECT="${G}✓ Correct$N"
WARNING="${Y}⚠$N"

TESTDIR="examples"

set -e

echo "-- Compile sources --"
make
echo ""

run_one() {
    local FULLNAME="$1"
    local TEST="$(basename -- "$FULLNAME" .m)"
    local FILE="$TESTDIR/$TEST"

    printf "${BOLD}Testcase: %s$N " "$TEST"

    COMM="./run -resonly $FILE.m > $FILE.out 2> $FILE.err"
    if [ -f "$FILE.in" ]; then
        COMM="$COMM < $FILE.in"
    fi

    if eval "$COMM"; then
        if diff "$FILE.ans" "$FILE.out" > /dev/null; then
            echo "$CORRECT"
        else
            echo "$WRONG"
            echo "${G}Answer:$N"
            cat "$FILE.ans"
            echo "${R}Output:$N"
            cat "$FILE.out"
            echo ""
        fi
    else
        echo "$WRONG"
        cat "$FILE.err"
    fi
}

echo "-- Testing Lowfat M --"
for FULLNAME in $(find "$TESTDIR"/*.m | sort -V); do
    run_one "$FULLNAME"
done
