#!/bin/bash

TESTDIR="examples"
WRONG="$(tput setaf 1)✗$(tput sgr0)"
CORRECT="$(tput setaf 2)✓$(tput sgr0)"

echo '# Compiling...'
if ! make
then
    echo ''
    echo 'Compile fail.'
    exit 1
fi
echo ''

run_one() {
    local TFILE="$1"
    local LABEL="$2"
    printf "Test %s..." "${LABEL}"

    COMM="./run -resonly ${TFILE}.m > ${TFILE}.out"
    if [ -f "${TFILE}.in" ]; then
        COMM="${COMM} < ${TFILE}.in"
    fi

    if eval "${COMM}" && diff "${TFILE}.ans" "${TFILE}.out" > /dev/null; then
        echo "${CORRECT}"
    else
        echo "${WRONG}"
        echo "== Answer =="
        cat "${TFILE}.ans"
        echo "== Output =="
        cat "${TFILE}.out"
    fi
}

echo '# Testing M Interpreter'
for FULLNAME in $(find "${TESTDIR}"/test*.m | sort -V); do
    TEST=$(basename "${FULLNAME}" .m)
    run_one "${TESTDIR}/${TEST}" "${TEST#test}"
done
