#!/bin/bash
HWNUM=1
EXERCISES=(1 2 3 4 5 6 7)
LIB_PATH="../lib/"
LIBSRC="testlib.ml"

check () {
    local ex="$1"
    local mode="$2"
    local src="ex${ex}.ml"
    local out="ex${ex}.out"

    echo "# Exercise ${ex}"
    ocamlc -I "${LIB_PATH}" -o "${out}" "${LIB_PATH}${LIBSRC}" "${src}" "test${ex}.ml" \
        && ./"${out}" ${mode}
}

if [[ $# -eq 0 ]]
then
    echo "== Homework ${HWNUM} =="
    for EX in "${EXERCISES[@]}"; do
        check "${EX}" summary
    done
elif [[ $# -eq 1 ]]
then
    VALID=0
    for EX in "${EXERCISES[@]}"; do
        if [[ "$1" -eq "${EX}" ]]
        then
            VALID=1
            break
        fi
    done
    if [[ "${VALID}" -eq 1 ]]
    then
        check "$1"
    else
        echo "Error: Exercise ${1} not found"
    fi
else
    echo "Error: Too many arguments"
fi