#!/bin/bash

R=$(tput setaf 1)
G=$(tput setaf 2)
Y=$(tput setaf 3)
N=$(tput sgr0)
BOLD=$(tput bold)

WRONG="${R}✗ Wrong$N"
CORRECT="${G}✓ Correct$N"
WARNING="${Y}⚠$N"

TESTDIR="examples"

set -e

echo "-- Compile sources --"
make
echo ""

echo "-- Testing Exception is Sugar --"
for FULLNAME in $(find "$TESTDIR"/test*.xexp | sort -V)
do
    TEST="$(basename -- "$FULLNAME" .xexp)"
    FILE="$TESTDIR/$TEST"

    printf "${BOLD}Testcase: %s$N " "$TEST"

    if ./run -checkval "$FILE.xexp" > /dev/null 2>&1; then
        echo "$CORRECT"
    else
        echo "$WRONG"
        ./run "$FILE.xexp" 2>&1 | head -10
    fi
done
